// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.prefabsoft.security.acl.model;

import java.lang.String;

privileged aspect PrefabAclClass_Roo_JavaBean {
    
    public String PrefabAclClass.getClazz() {
        return this.clazz;
    }
    
    public void PrefabAclClass.setClazz(String clazz) {
        this.clazz = clazz;
    }
    
}
