// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.prefabsoft.security.acl.model;

import java.lang.String;

privileged aspect PrefabAclClass_Roo_ToString {
    
    public String PrefabAclClass.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Clazz: ").append(getClazz());
        return sb.toString();
    }
    
}
